version: "3.8"

services:
  app:
    container_name: app
    image: flask
    #restart: on-failure
    dns: 8.8.8.8
    networks:
      - lan
    ports:
      - 80:5000
    #working_dir: /app
    volumes:
      - .:/app

networks:
  lan:
    ipam: 
      driver: default
      config:
        - subnet: 192.168.20.0/24
            
    